version: "3"
services:
  web:
    build: ./frontend
    container_name: web
    ports:
      - 80:80
      - 443:443
      - 4200:4200
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - app-network
    env_file:
      - .env

  api:
    build: ./backend
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./api/:/app
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: iatecam
      POSTGRES_USER: iatecam
      POSTGRES_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
