"""add column for softdelete Category

Revision ID: 5e57a3407e9f
Revises: 8d907b43a43b
Create Date: 2022-10-30 10:25:48.618893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e57a3407e9f'
down_revision = '8d907b43a43b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column(
        'is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
